### ISSUE TITLE
下载好以后不会用啊，安装了go，在文件目录运行go build就报错

### ISSUE THREAD

**Issue by hardtosetaname** [unlock-music/simple-server#1]
PS E:\giteeDownlode\simple-server-master> go generate
go: github.com/pkg/browser@v0.0.0-20180916011732-0a3d74bf9ce4: Get "https://proxy.golang.org/github.com/pkg/browser/@v/v0.0.0-20180916011732-0a3d74bf9ce4.mod": dial tcp 216.58.199.17:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
PS E:\giteeDownlode\simple-server-master> cd builder
PS E:\giteeDownlode\simple-server-master\builder> go generate
go: github.com/pkg/browser@v0.0.0-20180916011732-0a3d74bf9ce4: Get "https://proxy.golang.org/github.com/pkg/browser/@v/v0.0.0-20180916011732-0a3d74bf9ce4.mod": dial tcp 142.250.199.81:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
PS E:\giteeDownlode\simple-server-master\builder> go build
go: github.com/pkg/browser@v0.0.0-20180916011732-0a3d74bf9ce4: Get "https://proxy.golang.org/github.com/pkg/browser/@v/v0.0.0-20180916011732-0a3d74bf9ce4.mod": dial tcp 142.250.199.81:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
PS E:\giteeDownlode\simple-server-master\builder>

**Comment by ix64** [comment]
中国大陆用户需要设置GOPROXY变量，具体方法参见 https://goproxy.io/zh/ 或&nbsp;https://mirrors.aliyun.com/goproxy/
----------

该邮件从移动设备发送




--------------原始邮件--------------
发件人："耶！ "<notifications@github.com&gt;;
发送时间：2021年1月10日(星期天) 下午4:28
收件人："unlock-music/simple-server" <simple-server@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：[unlock-music/simple-server] 下载好以后不会用啊，安装了go，在文件目录运行go build就报错 (#1)
-----------------------------------

 

 
PS E:\giteeDownlode\simple-server-master&gt; go generate
 go: github.com/pkg/browser@v0.0.0-20180916011732-0a3d74bf9ce4: Get "https://proxy.golang.org/github.com/pkg/browser/@v/v0.0.0-20180916011732-0a3d74bf9ce4.mod": dial tcp 216.58.199.17:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 PS E:\giteeDownlode\simple-server-master&gt; cd builder
 PS E:\giteeDownlode\simple-server-master\builder&gt; go generate
 go: github.com/pkg/browser@v0.0.0-20180916011732-0a3d74bf9ce4: Get "https://proxy.golang.org/github.com/pkg/browser/@v/v0.0.0-20180916011732-0a3d74bf9ce4.mod": dial tcp 142.250.199.81:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 PS E:\giteeDownlode\simple-server-master\builder&gt; go build
 go: github.com/pkg/browser@v0.0.0-20180916011732-0a3d74bf9ce4: Get "https://proxy.golang.org/github.com/pkg/browser/@v/v0.0.0-20180916011732-0a3d74bf9ce4.mod": dial tcp 142.250.199.81:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 PS E:\giteeDownlode\simple-server-master\builder&gt;
